version: "3.8"
services:
  node:
    image: node:16.15.1-bullseye
    user: node:node
    working_dir: /home/node/accessible-navbar
    volumes:
      - ./:/home/node/accessible-navbar
    environment:
      - YARN_CACHE_FOLDER=/home/node/accessible-navbar/.cache/yarn
      # - INTERNAL_STATUS_PORT=33000
    ports:
      - 9000:9000
    command: tail -F anything
